In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("jobs.csv")

raw_df = df.copy()
clean_df = df.copy()

print(f"Tổng số bản ghi: {clean_df.shape[0]:,}")
print(f"Tổng số cột: {clean_df.shape[1]}")

clean_df.head()

Tổng số bản ghi: 85,470
Tổng số cột: 11

,job_title,job_type,position_level,city,experience,skills,job_fields,salary,salary_min,salary_max,unit
0,trưởng phòng kinh doanh,nhân viên chính thức,"trưởng nhóm , giám sát",hồ chí minh,lên đến 1 năm,NaN,"kinh doanh, bán hàng, nội ngoại thất, xây dựng",15 tr - 50 tr vnd,15.0,50.0,vnd
1,nhân viên qc ngành cơ khí,nhân viên chính thức,nhân viên,hồ chí minh,trên 1 năm,"production planning staff, chuyên viên iso, th...","vận hành sản xuất, sản xuất, qc), quản lý chất...",8 tr - 11 tr vnd,8.0,11.0,vnd
2,trưởng phòng đấu thầu,nhân viên chính thức,"trưởng nhóm , giám sát",hồ chí minh,5 - 7 năm,"trưởng phòng xây dựng, trưởng phòng đấu thầu, ...","điện, xây dựng, điện tử, điện lạnh, dầu khí, đ...",20 tr - 30 tr vnd,20.0,30.0,vnd
3,home textile designer,nhân viên chính thức,nhân viên,hưng yên,5 - 15 năm,NaN,"dệt may, nghệ thuật, da giày, thiết kế, mỹ thu...","800 - 1,500 usd",20.0,37.5,usd
4,nhân viên kinh doanh,nhân viên chính thức,nhân viên,hồ chí minh,trên 1 năm,NaN,"tư vấn, bán sỉ, bán lẻ, kinh doanh, bán hàng",10 tr - 50 tr vnd,10.0,50.0,vnd

In [2]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 85470 entries, 0 to 85469
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_title       85463 non-null  str
 1   job_type        85470 non-null  str
 2   position_level  85470 non-null  str
 3   city            85438 non-null  str
 4   experience      85470 non-null  str
 5   skills          74176 non-null  str
 6   job_fields      77845 non-null  str
 7   salary          85470 non-null  str
 8   salary_min      85470 non-null  float64
 9   salary_max      85470 non-null  float64
 10  unit            85470 non-null  str
dtypes: float64(2), str(9)
memory usage: 7.2 MB

In [3]:
def audit_data(dataframe):
    """
    Hàm tự động thống kê giá trị khuyết thiếu và giá trị duy nhất cho từng cột
    """
    audit_df = pd.DataFrame({
        "Kiểu dữ liệu": dataframe.dtypes,
        "Số lượng khuyết": dataframe.isna().sum(),
        "Tỷ lệ khuyết (%)": (dataframe.isna().mean() * 100).round(2),
        "Số giá trị duy nhất (Unique)": dataframe.nunique(),
        "Mẫu dữ liệu": dataframe.iloc[0]
    })
    return audit_df.sort_values("Tỷ lệ khuyết (%)", ascending=False)
audit_data(clean_df)

,Kiểu dữ liệu,Số lượng khuyết,Tỷ lệ khuyết (%),Số giá trị duy nhất (Unique),Mẫu dữ liệu
skills,str,11294,13.21,20484,NaN
job_fields,str,7625,8.92,7491,"kinh doanh, bán hàng, nội ngoại thất, xây dựng"
city,str,32,0.04,466,hồ chí minh
job_title,str,7,0.01,23576,trưởng phòng kinh doanh
job_type,str,0,0.00,27,nhân viên chính thức
position_level,str,0,0.00,26,"trưởng nhóm , giám sát"
experience,str,0,0.00,181,lên đến 1 năm
salary,str,0,0.00,2069,15 tr - 50 tr vnd
salary_min,float64,0,0.00,190,15.0
salary_max,float64,0,0.00,175,50.0
unit,str,0,0.00,2,vnd

In [4]:
clean_df[["salary_min", "salary_max"]].describe().T

              count       mean        std  min   25%   50%   75%    max
salary_min  85470.0  11.875715  14.763057  0.0   8.0  10.0  15.0  900.0
salary_max  85470.0  19.191847  16.023232  0.0  12.0  15.0  21.0  700.0

In [5]:
city_mapping = {
    "hà nội": "Hanoi",
    "hanoi": "Hanoi",
    "ha noi": "Hanoi",
    "hà nộ": "Hanoi",
    "hà hội": "Hanoi",
    "cầu giấy": "Hanoi",
    "q cầu giấy": "Hanoi",
    "quận cầu giấy": "Hanoi",
    "thanh xuân": "Hanoi",
    "quận thanh xuân": "Hanoi",
    "hoàng mai": "Hanoi",
    "quận hoàng mai": "Hanoi",
    "hai bà trưng": "Hanoi",
    "quận hai bà trưng": "Hanoi",
    "ba đình": "Hanoi",
    "quận ba đình": "Hanoi",
    "đống đa": "Hanoi",
    "quận đống đa": "Hanoi",
    "hoàn kiếm": "Hanoi",
    "quận hoàn kiếm": "Hanoi",
    "hà đông": "Hanoi",
    "quận hà đông": "Hanoi",
    "hà đông": "Hanoi",
    "nam từ liêm": "Hanoi",
    "bắc từ liêm": "Hanoi",
    "quận bắc từ liêm": "Hanoi",
    "từ liêm": "Hanoi",
    "long biên": "Hanoi",
    "huyện gia lâm": "Hanoi",
    "thanh trì": "Hanoi",
    "huyện mê linh": "Hanoi",
    "huyện phú xuyên": "Hanoi",
    "phú xuyên": "Hanoi",
    "trung hòa": "Hanoi",
    "trung văn": "Hanoi",
    "đại kim": "Hanoi",
    "phương liệt": "Hanoi",
    "kim mã": "Hanoi",
    "cổ nhuế": "Hanoi",
    "cổ nhuế 1": "Hanoi",
    "cổ nhuế 2": "Hanoi",
    "phường cổ nhuế 1": "Hanoi",
    "phường cổ nhuế 2": "Hanoi",
    "phường dịch vọng hậu": "Hanoi",
    "lotte mall tây hồ": "Hanoi",
    "quận tây hồ": "Hanoi",
    "tây hồ": "Hanoi",

    "hồ chí minh": "Ho Chi Minh City",
    "ho chi minh": "Ho Chi Minh City",
    "ho chi minh city": "Ho Chi Minh City",
    "hcm": "Ho Chi Minh City",
    "phường 13 quận 10": "Ho Chi Minh City",

    "đà nẵng": "Da Nang",
    "da nang": "Da Nang",

    "hải phòng": "Hai Phong",
    "tp hải phòng": "Hai Phong",

    "cần thơ": "Can Tho",

    "bình dương": "Binh Duong",
    "bd": "Binh Duong",

    "đồng nai": "Dong Nai",
    "dong nai province": "Dong Nai",
    "biên hòa": "Dong Nai",

    "huyện yên mỹ": "Hung Yen"
}

clean_df["city_cleaned"] = clean_df["city"].astype(str).str.strip().str.lower()
clean_df["city_cleaned"] = clean_df["city_cleaned"].replace(city_mapping)

clean_df["city"] = clean_df["city_cleaned"]
clean_df.drop(columns=["city_cleaned"], inplace=True)

In [6]:
top_cities = clean_df["city"].value_counts().head(10).reset_index()
top_cities.columns = ["Thành phố / Tỉnh", "Số lượng tin tuyển dụng"]
top_cities

   Thành phố / Tỉnh  Số lượng tin tuyển dụng
0             Hanoi                    27307
1  Ho Chi Minh City                    26100
2        Binh Duong                     3741
3          Dong Nai                     2623
4         Hai Phong                     1663
5           long an                     1612
6           Da Nang                     1391
7          hưng yên                     1119
8          bắc ninh                     1042
9          tây ninh                      696

In [7]:
clean_df["skills"] = clean_df["skills"].fillna("Chưa cập nhật")
clean_df["job_fields"] = clean_df["job_fields"].fillna("Chưa cập nhật")

mask = clean_df["salary_min"] > clean_df["salary_max"]
clean_df.loc[mask, ["salary_min", "salary_max"]] = clean_df.loc[mask, ["salary_max", "salary_min"]].values

audit_data(clean_df)

,Kiểu dữ liệu,Số lượng khuyết,Tỷ lệ khuyết (%),Số giá trị duy nhất (Unique),Mẫu dữ liệu
city,str,32,0.04,414,Ho Chi Minh City
job_title,str,7,0.01,23576,trưởng phòng kinh doanh
job_type,str,0,0.00,27,nhân viên chính thức
position_level,str,0,0.00,26,"trưởng nhóm , giám sát"
experience,str,0,0.00,181,lên đến 1 năm
skills,str,0,0.00,20485,Chưa cập nhật
job_fields,str,0,0.00,7492,"kinh doanh, bán hàng, nội ngoại thất, xây dựng"
salary,str,0,0.00,2069,15 tr - 50 tr vnd
salary_min,float64,0,0.00,168,15.0
salary_max,float64,0,0.00,196,50.0
unit,str,0,0.00,2,vnd

In [8]:
clean_df.to_csv("jobs_cleaned.csv", index=False, encoding="utf-8-sig")
print("Đã xuất file dữ liệu hoàn chỉnh: jobs_cleaned.csv")

Đã xuất file dữ liệu hoàn chỉnh: jobs_cleaned.csv